services:
  redis:
    image: redis:7-alpine
    container_name: redis-jurnee
    ports:
      - "6379:6379"
    volumes:
      - jurnee_redis:/data
    restart: unless-stopped

volumes:
  jurnee_redis: